---
- name: Configure NTP Client on RHEL8
  hosts: aws_ec2
  gather_facts: yes
  vars_files:
    - ./credentials/redhat-activation-key.yml

  tasks:

    - name: Register with activationkey and consume subscriptions matching Red Hat Enterprise Linux Server
      redhat_subscription:
        state: present
        activationkey: "{{ rhactivationkey }}"
        org_id: "{{ rhorg_id }}"
        auto_attach: true
      become: yes

    - name: upgrade all packages
      yum:
        name: '*'
        state: latest
      become: yes

    - name: install packages
      ansible.builtin.yum:
        name: "{{ packages }}"
      vars:
        packages:
        - chrony
        - vim
      become: yes

    - name: Ensure NTP Client is running
      ansible.builtin.service:
        name: chronyd
        state: started
      become: yes

    - name: Add NTP Servers to proper location
      ansible.builtin.template:
        src: "{{ playbook_dir }}/templates/rhel8-aws-ntp-client.j2"
        dest: /etc/chrony.conf
      become: yes
      notify:
      - Restart NTP Client

  handlers:

    - name: Restart NTP Client
      ansible.builtin.service:
        name: chronyd
        state: restarted
      become: yes