---
- name: Install Latest Ansible Tower on RHEL8
  hosts: rhel
  gather_facts: yes
  vars_files:
    - ./credentials/redhat-activation-key.yml

  tasks:

    - name: Register with activationkey and consume subscriptions matching Red Hat Enterprise Linux Server
      redhat_subscription:
        state: present
        activationkey: "{{ rhactivationkey }}"
        org_id: "{{ rhorg_id }}"
        auto_attach: true
      become: yes

    - name: upgrade all packages
      yum:
        name: '*'
        state: latest
      become: yes

    - name: install packages
      yum:
        name: "{{ packages }}"
      vars:
        packages:
        - wget
        - tar
        - python3-pip
      become: yes

    - name: Download Ansible Tower
      get_url:
        url: https://releases.ansible.com/ansible-tower/setup/ansible-tower-setup-latest.tar.gz
        dest: /tmp/tower.tar.gz

    - name: Create directory for Ansible Tower
      file: path=/tmp/tower_install state=directory

    - name: Extract Ansible Tower install
      unarchive:
        src: /tmp/tower.tar.gz
        dest: /tmp/tower_install
        remote_src: true
        extra_opts: ['--strip-components=1', '--show-stored-names']

    - name: template inventory file for Ansible Tower Install
      template:
        src: ./templates/tower_install.j2
        dest: /tmp/tower_install/inventory

    - name: run the Ansible Tower installer
      shell: ./setup.sh
      args:
        chdir: /tmp/tower_install
      async: 1400
      poll: 15
      become: yes

    - name: install ansible-tower-cli and requests
      become: true
      pip:
        name:
          - ansible-tower-cli
          - "requests==2.6.0"
        state: latest
