---
- name: Apply Letsencrypt Certificate to Ansible Tower
  hosts: rhel
  gather_facts: yes
  vars_files:
    - ./vars/default-vars.yml

  tasks:

    - name: install ansible-tower-cli and requests
      become: true
      pip:
        name:
          - ansible-tower-cli
          - "requests==2.6.0"
        state: latest

    - name: Download and install certbot
      get_url:
        url: https://dl.eff.org/certbot-auto
        dest: /usr/local/bin/certbot-auto
        mode: '0755'
        owner: "root"
      become: yes

    # https://docs.ansible.com/ansible-tower/latest/html/administration/init_script.html
    - name: turn off Ansible Tower
      shell: ansible-tower-service stop
      become: yes

    - name: SSL cert block
      block:
        # If this fails check out status of certbot: https://letsencrypt.status.io/
        - name: ISSUE CERT
          shell: /usr/local/bin/certbot-auto certonly --no-bootstrap --standalone -d {{ cert_domain }} --email {{ email }} --noninteractive --agree-tos
          register: issue_cert
          until: issue_cert is not failed
          retries: 5

        - name: MOVE SSL KEY
          copy:
            remote_src: true
            src: "/etc/letsencrypt/live/{{ cert_domain }}/privkey.pem"
            dest: /etc/tower/tower.key
          become: yes

        - name: GRAB SPECIFIC SSL CERT
          slurp:
            src: "/etc/letsencrypt/live/{{ cert_domain }}/cert.pem"
          register: intermediate_cert
          become: yes

        - name: COMBINE SPECIFIC AND INTERMEDIATE CERT
          template:
            src: ./templates/combined_cert.j2
            dest: /etc/tower/tower.cert
          become: yes

        - name: turn on tower
          shell: ansible-tower-service start
          register: install_tower
          until: install_tower is not failed
          retries: 5
          become: yes

      rescue:
        - name: turn on tower
          shell: ansible-tower-service start
          register: install_tower
          until: install_tower is not failed
          retries: 5
          become: yes

        - name: fail on purpose
          debug:
            msg: "failing on purpose - SSL cert problem"
          failed_when: true
