---
deploy_application:
  author: "Sean Cavanaugh"
  readme: "https://github.com/ansible/product-demos/blob/master/docs/infrastructure/deploy_application.md"
  category: infrastructure
  name: "INFRASTRUCTURE / Deploy Application"
  description: "install yum applications on Linux with a survey"
  job_type: "run"
  inventory: "Workshop Inventory"
  playbook: "playbooks/infrastructure/deploy_application.yml"
  credential: "Workshop Credential"
  survey_enabled: true
  survey_spec:
    name: Deploy application survey
    description: Which application do you want to install?
    spec:
      - type: multiplechoice
        question_name: Select a command you would like to execute
        question_description: select the application
        variable: application
        required: true
        default: httpd
        choices:
          - httpd
          - nginx
          - htop
          - gdb
  video: "https://www.youtube.com/watch?v=pU8ZgSBuEJw&list=PLdu06OJoEf2bp-PNtxPP_2n7Avkax8TED"
  project:
    name: "Ansible official demo project"
    description: "prescriptive demos from Red Hat Management Business Unit"
    organization: "Default"
    scm_type: git
    scm_url: "https://github.com/ansible/product-demos"
  workshop_type:
    - f5
    - rhel
    - rhel_90
    - demo
