---
grant_sudo:
  author: "Will Tome"
  category: infrastructure
  name: "INFRASTRUCTURE / Grant Sudo"
  description: "grant sudo privledges for specified time via survey"
  job_type: "run"
  inventory: "Workshop Inventory"
  playbook: "playbooks/infrastructure/grant_sudo.yml"
  credential: "Workshop Credential"
  survey_enabled: true
  survey_spec:
    name: ''
    description: ''
    spec:
      - question_name: 'Enter host to configure'
        type: text
        variable: HOSTS
        required: false
      - question_name: Username
        type: text
        variable: sudo_user
        required: true
      - question_name: Time
        type: integer
        variable: sudo_count
        required: true
        default: 10
      - question_name: Units
        type: multiplechoice
        variable: harden_ssh
        required: true
        choices:
          - 'minutes'
          - 'hours'
          - 'days'
        default: minutes
  project:
    name: "Ansible official demo project"
    description: "prescriptive demos from Red Hat Management Business Unit"
    organization: "Default"
    scm_type: git
    scm_url: "https://github.com/ansible/product-demos"
  workshop_type:
    - f5
    - rhel
    - rhel_90
    - demo
