---
insights:
  author: "Sean Cavanaugh"
  category: infrastructure
  name: "INFRASTRUCTURE / Red Hat Insights"
  description: "install and configure Red Hat Insights"
  job_type: "run"
  inventory: "Workshop Inventory"
  playbook: "playbooks/infrastructure/insights.yml"
  credential: "Workshop Credential"
  survey_enabled: true
  survey_spec:
    name: ''
    description: ''
    spec:
      - question_name: 'Enter your Red Hat customer portal username'
        type: text
        variable: redhat_portal_username
        required: true
      - question_name: 'Enter your Red Hat customer portal passowrd'
        type: password
        variable: redhat_portal_password
        required: true
  project:
    name: "Ansible official demo project"
    description: "prescriptive demos from Red Hat Management Business Unit"
    organization: "Default"
    scm_type: git
    scm_url: "https://github.com/ansible/product-demos"
  workshop_type:
    - f5
    - rhel
    - rhel_90
    - demo
