---
turn_off_community_grid:
  author: "Sean Cavanaugh"
  category: infrastructure
  name: "INFRASTRUCTURE / Turn off IBM Community Grid"
  description: "this role turns off IBM Community Grid boinc-client"
  job_type: "run"
  inventory: "Workshop Inventory"
  playbook: "playbooks/infrastructure/turn_off_community_grid.yml"
  credential: "Workshop Credential"
  survey_enabled: false
  project:
    name: "Ansible official demo project"
    description: "prescriptive demos from Red Hat Management Business Unit"
    organization: "Default"
    scm_type: git
    scm_url: "https://github.com/ansible/product-demos"
  workshop_type:
    - f5
    - rhel
    - rhel_90
    - demo
