---
windows_iis:
  author: "Colin McNaughton"
  category: infrastructure
  name: "SERVER / Windows IIS Server"
  description: "install webserver on Windows Server with a survey"
  job_type: "run"
  inventory: "Workshop Inventory"
  playbook: "playbooks/infrastructure/windows_iis.yml"
  credential: "Workshop Credential"
  survey_enabled: false
  project:
    name: "Ansible official demo project"
    description: "prescriptive demos from Red Hat Management Business Unit"
    organization: "Default"
    scm_type: git
    scm_url: "https://github.com/ansible/product-demos"
  workshop_type:
    - windows
    - demo
