---
- name: "INSIDE LOOP - install all job templates in relation to workflow {{ item.value.name }}"
  include_tasks: job_template_loop.yml
  loop: "{{ item.value.job_templates|dict2items }}"

- name: "INSIDE LOOP - install workflow template {{ item.value.name }}"
  tower_workflow_template:
    name: "{{ item.value.name }}"
    description: "{{ item.value.description }}"
    organization: "{{ item.value.organization }}"
    schema: "{{ item.value.schema }}"
    tower_username: "{{ my_tower_username }}"
    tower_password: "{{ my_tower_password }}"
    tower_host: "{{ my_tower_host }}"
    validate_certs: false
