- name: "Determine whether git repo {{ item.dest_name }} exists for non-root user"
  ansible.builtin.stat:
    path: "/home/{{ hostvars[groups['buildserver'][0]].ansible_user }}/git-workspace/{{ item.dest_name }}"
  register: k8s_repo_directory
  when: hostvars[groups['buildserver'][0]].ansible_user != "root"
  
- name: "Determine whether git repo {{ item.dest_name }} exists for root user"
  ansible.builtin.stat:
    path: "/root/git-workspace/{{ item.dest_name }}"
  register: k8s_repo_directory
  when: hostvars[groups['buildserver'][0]].ansible_user == "root"

- name: Clone repo for non-root user
  ansible.builtin.git:
    repo: "{{ item.repo_name }}"
    version: "{{ item.repo_branch }}"
    dest: "/home/{{ hostvars[groups['buildserver'][0]].ansible_user }}/git-workspace/{{ item.dest_name }}"
  when: not k8s_repo_directory.stat.exists and hostvars[groups['buildserver'][0]].ansible_user != "root"

- name: Clone repo for root user
  ansible.builtin.git:
    repo: "{{ item.repo_name }}"
    version: "{{ item.repo_branch }}"
    dest: "/root/git-workspace/{{ item.dest_name }}"
  when: not k8s_repo_directory.stat.exists and hostvars[groups['buildserver'][0]].ansible_user == "root"