---
galaxy_info:
  role_name: install_demo
  author: Sean Cavanaugh
  description: |
    This role will install demos into your specified Ansible Tower environment.
  company: Red Hat
  platforms:
    - name: EL
      versions:
        - 8
        - 7

  license: GPL-3.0-or-later

  min_ansible_version: 2.9

  galaxy_tags: []
dependencies: []
